<?php

/**
 * Block editor (gutenberg) specific functionality
 *
 * @package Thenewlook
 */


add_action('after_setup_theme', 'understrap_block_editor_setup');

if (!function_exists('understrap_block_editor_setup')) {

	/**
	 * Sets up our default theme support for the WordPress block editor.
	 *
	 */
	function understrap_block_editor_setup()
	{

		// Add support for the block editor stylesheet.
		add_theme_support('editor-styles');

		// Add support for wide alignment.
		add_theme_support('align-wide');

		// Register our custom colors as options in the editor.
		$color_palette = understrap_generate_color_palette();
		if ($color_palette) {
			add_theme_support('editor-color-palette', $color_palette);
		}
	}
}

if (!function_exists('understrap_generate_color_palette')) {
	/**
	 * Checks for our JSON file of color values. If exists, creates a color palette array.
	 *
	 * @return array|bool
	 */
	function understrap_generate_color_palette()
	{
		$color_palette = array();

		// Grabs the autogenerated color palette that we're pulling from our compiled bootstrap stylesheets.
		$color_palette_json = file_get_contents(get_theme_file_path('/inc/editor-color-palette.json')); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents

		if ($color_palette_json) {
			$color_palette_json = json_decode($color_palette_json, true);
			foreach ($color_palette_json as $key => $value) {
				$key             = ltrim($key, '--');
				$color_palette[] = array(
					'name'  => $key,
					'slug'  => $key,
					'color' => $value,
				);
			}
		}

		/**
		 * Filters the default bootstrap color palette so it can be overriden by child themes or plugins when we add theme support for editor-color-palette. This array can also be generated via gulp.
		 *
		 * @param array $color_palette An array of color options for the editor-color-palette setting.
		 */
		return apply_filters('understrap_theme_editor_color_palette', $color_palette);
	}
}

add_action('acf/init', 'my_acf_init');
function my_acf_init()
{

	if (function_exists('acf_register_block')) {
		acf_register_block(array(
			'name'            => 'image-with-bg',
			'title'           => __('Image with background image', 'thenewlook'),
			'description'     => __('A custom Image with background image block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'button',
			'keywords'        => array('image', 'images', 'background'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'multiple-price-list',
			'title'           => __('Multiple price list', 'thenewlook'),
			'description'     => __('A custom Multiple price list block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-helicopter" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
										<path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
										<path d="M3 10l1 2h6"></path>
										<path d="M12 9a2 2 0 0 0 -2 2v3c0 1.1 .9 2 2 2h7a2 2 0 0 0 2 -2c0 -3.31 -3.13 -5 -7 -5h-2z"></path>
										<line x1="13" y1="9" x2="13" y2="6"></line>
										<line x1="5" y1="6" x2="20" y2="6"></line>
										<path d="M15 9.1v3.9h5.5"></path>
										<line x1="15" y1="19" x2="15" y2="16"></line>
										<line x1="19" y1="19" x2="11" y2="19"></line>
									</svg>',
			'keywords'        => array('list', 'price'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'services',
			'title'           => __('Services', 'thenewlook'),
			'description'     => __('A custom Services block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-hotel-service" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
										<path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
										<path d="M8.5 10a1.5 1.5 0 0 1 -1.5 -1.5a5.5 5.5 0 0 1 11 0v10.5a2 2 0 0 1 -2 2h-7a2 2 0 0 1 -2 -2v-2c0 -1.38 .71 -2.444 1.88 -3.175l4.424 -2.765c1.055 -.66 1.696 -1.316 1.696 -2.56a2.5 2.5 0 1 0 -5 0a1.5 1.5 0 0 1 -1.5 1.5z"></path>
									</svg>',
			'keywords'        => array('services', 'price'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'bg-section',
			'title'           => __('Content (background color)', 'thenewlook'),
			'description'     => __('A custom Content (background color) block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('content', 'background'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'single-price-list',
			'title'           => __('Single price list', 'thenewlook'),
			'description'     => __('A custom single price list block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('list', 'price'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'pricelist-text',
			'title'           => __('Single price list & content', 'thenewlook'),
			'description'     => __('A custom Single price list & content block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('list', 'price', 'content'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'widget-posts-list',
			'title'           => __('Widget posts list', 'thenewlook'),
			'description'     => __('A custom widget posts list.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('posts', 'widget', 'list'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'faq',
			'title'           => __('FAQ', 'thenewlook'),
			'description'     => __('A custom FAQ block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('faq'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'choose-posts',
			'title'           => __('Choose posts', 'thenewlook'),
			'description'     => __('A custom choose posts block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('posts', 'blog'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));

		acf_register_block(array(
			'name'            => 'choose-posts-with-category',
			'title'           => __('Choose posts with category', 'thenewlook'),
			'description'     => __('A custom choose posts block.', 'thenewlook'),
			'render_callback' => 'my_acf_block_render_callback',
			'category'        => 'formatting',
			'icon'            => 'desktop',
			'keywords'        => array('posts', 'blog'),
			'mode'            => 'edit',
			'supports'        => array('align' => false),
		));
	}
}

function my_acf_block_render_callback($block)
{

	$slug = str_replace('acf/', '', $block['name']);
	if (file_exists(get_theme_file_path("/template-parts/block/content-{$slug}.php"))) {
		include(get_theme_file_path("/template-parts/block/content-{$slug}.php"));
	}
}

add_action('init', function (): void {
	$block_json_files = glob(get_theme_file_path('/blocks/*/block.json'));

	if (empty($block_json_files)) {
		return;
	}

	foreach ($block_json_files as $block_json_file) {
		register_block_type($block_json_file);
	}
});

function wpdc_add_custom_gutenberg_color_palette()
{
	add_theme_support(
		'editor-color-palette',
		[
			[
				'name'  => esc_html__('woocommerce', 'thenewlook'),
				'slug'  => 'woocommerce1',
				'color' => '#6F42C1',
			],
			[
				'name'  => esc_html__('woocommerce', 'thenewlook'),
				'slug'  => 'woocommerce2',
				'color' => '#9B51E0',
			],
			[
				'name'  => esc_html__('woocommerce', 'thenewlook'),
				'slug'  => 'woocommerce3',
				'color' => '#7F54B3',
			],
			[
				'name'  => esc_html__('woocommerce', 'thenewlook'),
				'slug'  => 'woocommerce4',
				'color' => '#674399',
			],
		]
	);
}
add_action('after_setup_theme', 'wpdc_add_custom_gutenberg_color_palette');
